---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: openai-dm-socket-server
spec:
  owner: me
---
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Socket-Server
spec:
  type: service
  lifecycle: unknown
  owner: me
  system: openai-dm-socket-server
  providesApi:
    - openai-dm-web-socket-api
---
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: openai-dm-web-socket-api
  annotations:
    github.com/project-slug: codeiain/openai-DM-Socket-Server
spec:
  type: asyncapi
  system:  openai-dm-socket-server
  lifecycle: unknown
  owner: me
  definition:
    $text: /asyncapi.yaml
---
    
    
