---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: openai-dm
  # annotations:
  #   backstage.io/techdocs-ref: dir:.
  #   github.com/project-slug: codeiain/openai-DM-character-service
spec:
  owner: iain
---
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: openai-dm-socket-server
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: codeiain/openai-DM-Socket-Server
spec:
  type: service
  lifecycle: unknown
  owner: iain
  system: openai-dm
  providesApi:
    - openai-dm-web-socket-api
  consumesApis:
    - openai-dm-character-api
    - openai-dm-auth-api
  dependsOn:
    - resource:prometheus
---
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: openai-dm-web-socket-api
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: codeiain/openai-DM-Socket-Server
spec:
  type: asyncapi
  system:  openai-dm
  lifecycle: unknown
  owner: iain
  definition:
    $text: /asyncapi.yaml
---
    
    
