---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: openAI-DM_Socket-Server
spec:
  owner: me
---
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Socket-Server
spec:
  type: service
  lifecycle: unknown
  owner: me
  system: openAI-DM_Socket-Server
  providesApi:
    - web-socket-api
---
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: web-socket-api
  annotations:
    github.com/project-slug: codeiain/openai-DM-Socket-Server
spec:
  type: asyncapi
  system:  openAI-DM_Socket-Server
  lifecycle: unknown
  owner: me
  definition:
    $text: /asyncapi.yaml
---
    
    
