---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: openAI-DM_Socket-Server
spec:
  owner: me
---
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: openAI-DM_Socket-Server1
spec:
  type: service
  owner: me
  system: openAI-DM_Socket-Server
  providesApi:
    - web-socket-api
