# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import msg_pb2 as protos_dot_msg__pb2


class msgStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GotMsg = channel.unary_unary(
                '/msg/GotMsg',
                request_serializer=protos_dot_msg__pb2.msg_request.SerializeToString,
                response_deserializer=protos_dot_msg__pb2.msg_responce.FromString,
                )


class msgServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GotMsg(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_msgServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GotMsg': grpc.unary_unary_rpc_method_handler(
                    servicer.GotMsg,
                    request_deserializer=protos_dot_msg__pb2.msg_request.FromString,
                    response_serializer=protos_dot_msg__pb2.msg_responce.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'msg', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class msg(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GotMsg(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/msg/GotMsg',
            protos_dot_msg__pb2.msg_request.SerializeToString,
            protos_dot_msg__pb2.msg_responce.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
